namespace Shared.Events.Tests;

public class IntegrationEventTests
{
    private record TestIntegrationEvent : IntegrationEvent
    {
        public string Name { get; init; } = string.Empty;
        public int Value { get; init; }
    }

    [Fact]
    public void IntegrationEvent_ShouldImplementIEventBase()
    {
        // Arrange & Act
        var integrationEvent = new TestIntegrationEvent { Name = "Test", Value = 123 };

        // Assert
        Assert.IsType<IEventBase>(integrationEvent, exactMatch: false);
    }

    [Fact]
    public void Id_WhenNotSet_ShouldBeAutoGenerated()
    {
        // Arrange & Act
        var integrationEvent = new TestIntegrationEvent { Name = "Test", Value = 123 };

        // Assert
        Assert.NotEqual(Guid.Empty, integrationEvent.MessageId);
    }

    [Fact]
    public void Id_WhenExplicitlySet_ShouldReturnSetValue()
    {
        // Arrange
        var expectedId = Guid.NewGuid();

        // Act
        var integrationEvent = new TestIntegrationEvent
        {
            Name = "Test",
            Value = 123,
            MessageId = expectedId,
        };

        // Assert
        Assert.Equal(expectedId, integrationEvent.MessageId);
    }

    [Fact]
    public void OccurredOnUtc_WhenNotSet_ShouldBeAutoGenerated()
    {
        // Arrange & Act
        var integrationEvent = new TestIntegrationEvent { Name = "Test", Value = 123 };

        // Assert
        Assert.NotEqual(default, integrationEvent.OccurredOnUtc);
    }

    [Fact]
    public void OccurredOnUtc_WhenExplicitlySet_ShouldReturnSetValue()
    {
        // Arrange
        var expectedDateTime = DateTime.UtcNow;

        // Act
        var integrationEvent = new TestIntegrationEvent
        {
            Name = "Test",
            Value = 123,
            OccurredOnUtc = expectedDateTime,
        };

        // Assert
        Assert.Equal(expectedDateTime, integrationEvent.OccurredOnUtc);
    }

    [Fact]
    public void Constructor_WhenCalledMultipleTimes_ShouldAllowDifferentIds()
    {
        // Arrange
        var id1 = Guid.NewGuid();
        var id2 = Guid.NewGuid();

        // Act
        var event1 = new TestIntegrationEvent
        {
            Name = "Test1",
            Value = 1,
            MessageId = id1,
        };
        var event2 = new TestIntegrationEvent
        {
            Name = "Test2",
            Value = 2,
            MessageId = id2,
        };

        // Assert
        Assert.NotEqual(event1.MessageId, event2.MessageId);
        Assert.Equal(id1, event1.MessageId);
        Assert.Equal(id2, event2.MessageId);
    }

    [Fact]
    public void Constructor_WhenCalledMultipleTimes_ShouldAllowDifferentOccurredOnUtcTimes()
    {
        // Arrange
        var time1 = DateTime.UtcNow;
        var time2 = DateTime.UtcNow.AddMinutes(1);

        // Act
        var event1 = new TestIntegrationEvent
        {
            Name = "Test1",
            Value = 1,
            OccurredOnUtc = time1,
        };
        var event2 = new TestIntegrationEvent
        {
            Name = "Test2",
            Value = 2,
            OccurredOnUtc = time2,
        };

        // Assert
        Assert.True(event2.OccurredOnUtc > event1.OccurredOnUtc);
        Assert.Equal(time1, event1.OccurredOnUtc);
        Assert.Equal(time2, event2.OccurredOnUtc);
    }

    [Fact]
    public void IntegrationEvent_WhenInitialized_ShouldHaveCorrectProperties()
    {
        // Arrange
        var name = "TestEvent";
        var value = 42;
        var id = Guid.NewGuid();
        var occurredOn = DateTime.UtcNow;

        // Act
        var integrationEvent = new TestIntegrationEvent
        {
            Name = name,
            Value = value,
            MessageId = id,
            OccurredOnUtc = occurredOn,
        };

        // Assert
        Assert.Equal(name, integrationEvent.Name);
        Assert.Equal(value, integrationEvent.Value);
        Assert.Equal(id, integrationEvent.MessageId);
        Assert.Equal(occurredOn, integrationEvent.OccurredOnUtc);
    }

    [Fact]
    public void Equals_WhenComparingDifferentEvents_ShouldReturnFalse()
    {
        // Arrange
        var event1 = new TestIntegrationEvent { Name = "Test1", Value = 1 };
        var event2 = new TestIntegrationEvent { Name = "Test2", Value = 2 };

        // Act
        var result = event1.Equals(event2);

        // Assert
        Assert.False(result);
        Assert.NotEqual(event1, event2);
    }

    [Fact]
    public void Equals_WhenComparingSameEvent_ShouldReturnTrue()
    {
        // Arrange
        var integrationEvent = new TestIntegrationEvent { Name = "Test", Value = 1 };

        // Act
        var result = integrationEvent.Equals(integrationEvent);

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void GetHashCode_WhenCalledOnDifferentEvents_ShouldReturnDifferentHashCodes()
    {
        // Arrange
        var event1 = new TestIntegrationEvent { Name = "Test1", Value = 1 };
        var event2 = new TestIntegrationEvent { Name = "Test2", Value = 2 };

        // Act
        var hashCode1 = event1.GetHashCode();
        var hashCode2 = event2.GetHashCode();

        // Assert
        Assert.NotEqual(hashCode1, hashCode2);
    }
}